FROM php:8.2-fpm

# Install sistem dependensi dan extension PHP
RUN apt-get update && apt-get install -y \
    git zip unzip libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo_mysql mbstring gd

# Set folder kerja
WORKDIR /var/www
COPY . .

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install --no-dev --optimize-autoloader

# Expose port & jalankan server
EXPOSE 8000
CMD php artisan serve --host=0.0.0.0 --port=8000